### ISSUE TITLE
Side animation

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#6] opened 2017-12-04 03:02 UTC
![screenshot 2](https://user-images.githubusercontent.com/20794390/33534437-4433492c-d8e2-11e7-84ba-c2b2f84b8b00.png)

@calvintam236 The arrow that points to the page which is currently selected only works for the pages currently supported. I added another page and i have included the animation.min.css file in this new page. Is there anything else i need to import to get the animation working on the new page created?

Thanks

**Comment by calvintam236** [comment] 2017-12-05 23:18
How is your animation effect works? It is based on `:hover`, or `:active`? Where is the `animation.min.css` you are referring to?

**Comment by pfeiflelukas** [comment] 2017-12-06 14:21
It is not hover as that still works. As far as i can tell hover boldens the words before the user clicks. The animation that doesnt work is the triangle/indent that indicates which page you are currently on. This is also helped by the word becoming orange/red. This also doesn't work on the new pages that i added.

So i believe it is an :active. I havent been able to find the corresponding piece of css yet.

**Comment by calvintam236** [comment] 2017-12-12 20:15
It is the how the theme was designed. You need to change `<li>` to `<li class="active">` for the indicator, which you need jQuery code. Color is pretty easy to change yourself. I'm gonna close this because this is theme customization, not technical problem.

**Closed by calvintam236** 2017-12-12 20:15 UTC

**Comment by pfeiflelukas** [comment] 2017-12-13 01:02
Just recognised the issue in the side navigation pane where dashboard.html was selected as "active" rather than the current page.

Thanks
